---
- name: Create EC2 instances in AWS
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: "ap-south-1"
    vpc_id: "vpc-05a6ec325cfcc6bf2"
    keypair: "mumbai"
    instance_type: "t3.micro"
    ami_id: "ami-03695d52f0d883f65"
    sg_name: "ansible-sg"
    instance_count: 3
    jenkins_pub_key: "/home/jenkins/.ssh/id_rsa.pub"
    inventory_file: "/home/jenkins/ansi.inv"
    aws_private_key: "/home/jenkins/.ssh/mumbai.pem"
    allowed_ports:
      - 22
      - 80
      - 443
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  tasks:

    # 1 - Create Security Group
    - name: Create a security group
      amazon.aws.ec2_security_group:
        name: "{{ sg_name }}"
        description: "Security group for EC2"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports: "{{ allowed_ports }}"
            cidr_ip: 0.0.0.0/0
      register: sg_info

    - debug:
        msg: "Created SG ID: {{ sg_info.group_id }}"

    # 2 - Launch EC2 Instances
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        name: "ansible-ec2"
        instance_type: "{{ instance_type }}"
        key_name: "{{ keypair }}"
        image_id: "{{ ami_id }}"
        region: "{{ region }}"
        security_group: "{{ sg_info.group_id }}"
        network:
          assign_public_ip: true
        count: "{{ instance_count }}"
        wait: yes
        wait_timeout: 600
      register: ec2_info

    - debug:
        msg: "Instance IDs: {{ ec2_info.instance_ids }}"

    # 3 - Save Private IPs into file
    - name: Save private IPs into inventory file
      copy:
        dest: "{{ inventory_file }}"
        content: |
          [ec2_nodes]
          {% for inst in ec2_info.instances %}
          {{ inst.private_ip_address }}
          {% endfor %}

    # 4 - Wait until SSH is available
    - name: Wait for SSH to be ready
      wait_for:
        host: "{{ item.public_ip_address }}"
        port: 22
        timeout: 400
        state: started
      loop: "{{ ec2_info.instances }}"

    # 5 - Add new instances to Ansible runtime inventory
    - name: Add instances to ec2_group
      ansible.builtin.add_host:
        name: "{{ item.public_ip_address }}"
        groups: ec2_group
      loop: "{{ ec2_info.instances }}"

######################################################################
#  — CREATE JENKINS USER + COPY SUDO FILE
######################################################################

- name: Create Jenkins user & setup SSH + sudo
  hosts: ec2_group
  gather_facts: false
  become: yes

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "/home/jenkins/.ssh/mumbai.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    jenkins_pub_key: "/home/jenkins/.ssh/id_rsa.pub"

  tasks:

    - name: Create jenkins user
      user:
        name: jenkins
        shell: /bin/bash
        create_home: yes

    - name: Create .ssh directory for jenkins
      file:
        path: /home/jenkins/.ssh
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0700'

    - name: Add Jenkins public key to jenkins authorized_keys
      authorized_key:
        user: jenkins
        key: "{{ lookup('file', jenkins_pub_key) }}"

    - name: Copy sudoers file for jenkins user
      copy:
        src: ./root_per_all        # <<< UPDATED HERE
        dest: /etc/sudoers.d/jenkins
        owner: root
        group: root
        mode: '0440'
