---
- name: Patch all EC2 instances
  hosts: ec2_nodes
  become: yes
  gather_facts: yes

  tasks:

    - name: Update packages on Amazon Linux / RHEL / CentOS
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update packages on Ubuntu / Debian
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Reboot if needed
      reboot:
        reboot_timeout: 600
      when: ansible_pkg_mgr in ["yum", "dnf", "apt"]
