---
<<<<<<< HEAD
- name: My First Playbook
  hosts: sapprod
  become: true
  gather_facts: false
  become_user: root
  tasks:
   - name: Create User
     user:
       name: alc-user
       password: $6$kdlafklakdj$jVBXr3pp3MyLrgxpTrdJJyGg6oiHyEKOA/Hk0XktvUZJExw6upj736L0Zgk6aLCJdH7yVtYTQVF/boZqubKNG/
       gecos: "This is service account for sap Admin"
      # state: present
       state: absent
... 
=======
- name: Create a user and add ssh public key to user's authorized keys
  hosts: localhost
  become: true
  remote_user: ansible
  tasks:
   - name: Add a user
     user:
       name: asian
       password: "{{ 'test123' | password_hash('sha512')}}"
       state: present
   # - name: Task to add SSH keys to the user
   #   authorized_key:
   #    user: asian
   #    state: present
   #    key: "{{lookup('file', '/home/ansible/id_rsa.pub')}}" 
...
>>>>>>> fc9bb4e783b9f5758e528280bf8dfdd91367dca5
