---
- name: Play to demonstrate unarchive
  hosts: [192.168.1.31, 192.168.1.32]
  become: true
  tasks:
   - name: Task to unarchive  
     unarchive:
      src: /tmp/etc_archive.tar.gz
      dest: /var/tmp
      remote_src: yes
...
