---
- name: Demonstration of raw module
#User raw module to execute command.
#used to execute command where there is no python installed 
#such as swtiches or routers etc.,
  hosts: localhost
  gather_facts: no
  become: true
  tasks:
  - name: execute command using raw module
    raw:
     uptime>/tmp/u.out
...

