---
- name: copy multiple file with loop
  hosts: [ 192.168.1.31, 192.168.1.32]
  become: yes
  vars:
   f_list:
    - orig: /etc/httpd/conf/httpd.conf
      destn: /var/tmp/httpd.conf
    - orig: /var/www/html/index.html
      destn: /var/tmp/index.html
  tasks:
  - name: copy files 
    copy:
     src: "{{item.orig}}"
     dest: "{{item.destn}}"
    loop: "{{f_list}}"
